In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/qianqiancuiapril/cyclist/202505-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202504-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202509-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202511-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202502-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202512-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202506-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202507-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202503-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202501-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202508-divvy-tripdata.csv
/kaggle/input/datasets/qianqiancuiapril/cyclist/202510-divvy-tripdata.csv

In [2]:
#Combine 2025 full year data into 1 csv file
import pandas as pd
import glob

files = glob.glob('/kaggle/input/datasets/qianqiancuiapril/cyclist/*.csv')
df_list = [pd.read_csv(f) for f in files]
full_year_data = pd.concat(df_list,ignore_index = True)

In [3]:
#check the total row number and column number to confirm the combination is finished
full_year_data.shape

(5552092, 13)

In [4]:
#export one version without any calculation
full_year_data.to_csv('/kaggle/working/cyclistic_data_raw.csv', index = False)

In [5]:
#added 2 columns: ride_length and day_of_week
#transfer format of ride_length from string to float(seconds) for further calculation
full_year_data['started_at'] = pd.to_datetime(full_year_data['started_at'])
full_year_data['ended_at'] = pd.to_datetime(full_year_data['ended_at'])
full_year_data['ride_length'] = full_year_data['ended_at'] - full_year_data['started_at'] 
full_year_data['ride_length'] = full_year_data['ride_length'].dt.total_seconds()
full_year_data['day_of_week'] = full_year_data['started_at'].dt.weekday + 1
full_year_data[['ride_length', 'day_of_week']]

         ride_length  day_of_week
0           2919.778            7
1            598.298            1
2            394.200            5
3            308.547            1
4            243.727            4
...              ...          ...
5552087      881.822            6
5552088      546.880            3
5552089      159.869            6
5552090      408.673            3
5552091      281.663            5

[5552092 rows x 2 columns]

In [6]:
#calculate mean and max of ride_length
#Calculate the mode of day_of_week
print(full_year_data['ride_length'].mean())
print(full_year_data['ride_length'].max())

965.791743957053
94494.011

In [7]:
#the max value of above calculation is very strange, I want to check the whole row
mask = full_year_data['ride_length'] == '1 days 02:14:54.011000'
full_year_data[mask]

Empty DataFrame
Columns: [ride_id, rideable_type, started_at, ended_at, start_station_name, start_station_id, end_station_name, end_station_id, start_lat, start_lng, end_lat, end_lng, member_casual, ride_length, day_of_week]
Index: []

In [8]:
#export data cleaned version
full_year_data.to_csv('/kaggle/working/cyclistic_data.csv', index = False)